env:
  node: true
  es6: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  # jest
  describe: readonly
  expect: readonly
  it: readonly
  xdescribe: readonly
  xit: readonly
  pending: readonly
plugins:
  - "@typescript-eslint"
  - prettier
  - simple-import-sort
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
rules:
  no-var: warn
  prefer-const: warn
  no-console: warn
  no-shadow: warn
  no-unused-expressions: warn
  curly: ["warn", "multi-line", "consistent"]
  spaced-comment: ["warn", "always"]
  simple-import-sort/sort: warn
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-empty-function": off
  "@typescript-eslint/no-empty-interface": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-this-alias": off
  "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }]
  "@typescript-eslint/explicit-function-return-type": ["warn", { allowExpressions: true }]
