dist: bionic
language: node_js
node_js:
  - "10"
  - "12"
  - "13"

# Override default install step
install: true

script:
  - ./scripts/travis.sh

# whitelist long living branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
  - master

notifications:
  email: false
